manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: AlexandrPK
      url-base: https://github.com/AlexandrPK
  projects:
    - name: zmk
      remote: AlexandrPK
      revision: pointers-move-scroll
      import: app/west.yml
  self:
    path: config
